[package]
name = "faster"
version = "0.1.0"
authors = ["Phoenix Kahlo <kahlo.phoenix@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "^1.3.0"
#ultraviolet = "^0.4.5"
packed_simd = { version = "^0.3.3", features = ["into_bits"] }